# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='interface.proto',
  package='demoserver',
  serialized_pb='\n\x0finterface.proto\x12\ndemoserver\"T\n\x13\x45ntitySearchRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x02(\t\x12\r\n\x05query\x18\x02 \x02(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"2\n\x13\x45ntityDetailRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x03(\x05\"#\n\x04Stat\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\")\n\rRelatedEntity\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x03(\x05\"\xd5\x01\n\x0e\x44\x65tailedEntity\x12\r\n\x05title\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\x05\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1e\n\x04stat\x18\x05 \x03(\x0b\x32\x10.demoserver.Stat\x12\x0e\n\x06topics\x18\x06 \x01(\t\x12\x0e\n\x06imgurl\x18\x07 \x01(\t\x12\x13\n\x0boriginal_id\x18\x08 \x01(\x05\x12\x31\n\x0erelated_entity\x18\t \x03(\x0b\x32\x19.demoserver.RelatedEntity\"f\n\x14\x45ntitySearchResponse\x12\r\n\x05query\x18\x01 \x02(\t\x12\x13\n\x0btotal_count\x18\x02 \x02(\x05\x12*\n\x06\x65ntity\x18\x03 \x03(\x0b\x32\x1a.demoserver.DetailedEntity\"5\n\tInfluence\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05topic\x18\x02 \x02(\x05\x12\r\n\x05score\x18\x03 \x02(\x01\"\x84\x01\n\x17InfluenceSearchResponse\x12\x11\n\tentity_id\x18\x01 \x02(\x05\x12(\n\tinfluence\x18\x02 \x03(\x0b\x32\x15.demoserver.Influence\x12,\n\rinfluenced_by\x18\x03 \x03(\x0b\x32\x15.demoserver.Influence')




_ENTITYSEARCHREQUEST = descriptor.Descriptor(
  name='EntitySearchRequest',
  full_name='demoserver.EntitySearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dataset', full_name='demoserver.EntitySearchRequest.dataset', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='demoserver.EntitySearchRequest.query', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='demoserver.EntitySearchRequest.offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='demoserver.EntitySearchRequest.count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=115,
)


_ENTITYDETAILREQUEST = descriptor.Descriptor(
  name='EntityDetailRequest',
  full_name='demoserver.EntityDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dataset', full_name='demoserver.EntityDetailRequest.dataset', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='demoserver.EntityDetailRequest.id', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=167,
)


_STAT = descriptor.Descriptor(
  name='Stat',
  full_name='demoserver.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='demoserver.Stat.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='demoserver.Stat.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=204,
)


_RELATEDENTITY = descriptor.Descriptor(
  name='RelatedEntity',
  full_name='demoserver.RelatedEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='demoserver.RelatedEntity.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='demoserver.RelatedEntity.id', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=206,
  serialized_end=247,
)


_DETAILEDENTITY = descriptor.Descriptor(
  name='DetailedEntity',
  full_name='demoserver.DetailedEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='demoserver.DetailedEntity.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='demoserver.DetailedEntity.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='demoserver.DetailedEntity.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='demoserver.DetailedEntity.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stat', full_name='demoserver.DetailedEntity.stat', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='topics', full_name='demoserver.DetailedEntity.topics', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imgurl', full_name='demoserver.DetailedEntity.imgurl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='original_id', full_name='demoserver.DetailedEntity.original_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='related_entity', full_name='demoserver.DetailedEntity.related_entity', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=250,
  serialized_end=463,
)


_ENTITYSEARCHRESPONSE = descriptor.Descriptor(
  name='EntitySearchResponse',
  full_name='demoserver.EntitySearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='query', full_name='demoserver.EntitySearchResponse.query', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total_count', full_name='demoserver.EntitySearchResponse.total_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='entity', full_name='demoserver.EntitySearchResponse.entity', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=465,
  serialized_end=567,
)


_INFLUENCE = descriptor.Descriptor(
  name='Influence',
  full_name='demoserver.Influence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='demoserver.Influence.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='topic', full_name='demoserver.Influence.topic', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='score', full_name='demoserver.Influence.score', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=569,
  serialized_end=622,
)


_INFLUENCESEARCHRESPONSE = descriptor.Descriptor(
  name='InfluenceSearchResponse',
  full_name='demoserver.InfluenceSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='demoserver.InfluenceSearchResponse.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='influence', full_name='demoserver.InfluenceSearchResponse.influence', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='influenced_by', full_name='demoserver.InfluenceSearchResponse.influenced_by', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=625,
  serialized_end=757,
)

_DETAILEDENTITY.fields_by_name['stat'].message_type = _STAT
_DETAILEDENTITY.fields_by_name['related_entity'].message_type = _RELATEDENTITY
_ENTITYSEARCHRESPONSE.fields_by_name['entity'].message_type = _DETAILEDENTITY
_INFLUENCESEARCHRESPONSE.fields_by_name['influence'].message_type = _INFLUENCE
_INFLUENCESEARCHRESPONSE.fields_by_name['influenced_by'].message_type = _INFLUENCE
DESCRIPTOR.message_types_by_name['EntitySearchRequest'] = _ENTITYSEARCHREQUEST
DESCRIPTOR.message_types_by_name['EntityDetailRequest'] = _ENTITYDETAILREQUEST
DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['RelatedEntity'] = _RELATEDENTITY
DESCRIPTOR.message_types_by_name['DetailedEntity'] = _DETAILEDENTITY
DESCRIPTOR.message_types_by_name['EntitySearchResponse'] = _ENTITYSEARCHRESPONSE
DESCRIPTOR.message_types_by_name['Influence'] = _INFLUENCE
DESCRIPTOR.message_types_by_name['InfluenceSearchResponse'] = _INFLUENCESEARCHRESPONSE

class EntitySearchRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYSEARCHREQUEST
  
  # @@protoc_insertion_point(class_scope:demoserver.EntitySearchRequest)

class EntityDetailRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYDETAILREQUEST
  
  # @@protoc_insertion_point(class_scope:demoserver.EntityDetailRequest)

class Stat(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STAT
  
  # @@protoc_insertion_point(class_scope:demoserver.Stat)

class RelatedEntity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RELATEDENTITY
  
  # @@protoc_insertion_point(class_scope:demoserver.RelatedEntity)

class DetailedEntity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DETAILEDENTITY
  
  # @@protoc_insertion_point(class_scope:demoserver.DetailedEntity)

class EntitySearchResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYSEARCHRESPONSE
  
  # @@protoc_insertion_point(class_scope:demoserver.EntitySearchResponse)

class Influence(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFLUENCE
  
  # @@protoc_insertion_point(class_scope:demoserver.Influence)

class InfluenceSearchResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFLUENCESEARCHRESPONSE
  
  # @@protoc_insertion_point(class_scope:demoserver.InfluenceSearchResponse)

# @@protoc_insertion_point(module_scope)
